name: Dev - CI

on:
  push:
    branches:
      - dev

jobs:
  build-linux:
    name: "Linux build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.14.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test //...

  build-mac:
    name: "Mac OS build"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel_osx"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.14.0/bazelisk-darwin-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-darwin-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...

  build-windows:
    name: "Windows OS build"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel_win"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.14.0/bazelisk-windows-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-windows-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...
