name: Documentation

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: "Linux Test and Build"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Bazel"
      uses: bazelbuild/setup-bazelisk@v2

    - name: "Mount bazel cache"
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: "Test All"
      run: bazel build //docs/...

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bazel-bin/docs/hugo_site