name: Release

on:
  push:
    tags:
    - '*release*'

jobs:
  build-linux:
    name: "Linux Build - Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Bazel Setup"
      uses: bazelbuild/setup-bazelisk@v2

    - name: "Mount Bazel cache"
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: "Build"
      run: bazel build //...

    - name: "Release - Linux"
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "bazel-bin/protoc-gen-bq-schema-*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    name: "Mac OS build - Release"
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Bazel"
      uses: bazelbuild/setup-bazelisk@v2

    - name: "Mount Bazel cache"
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: "Test"
      run: bazel build //...

    - name: "Release - Mac"
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "bazel-bin/protoc-gen-bq-schema-*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}