name: Release

on:
  push:
    tags:
    - '*release*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel_linux"
        key: bazel

    - name: Build
      run: bazel build //...

    - uses: ncipollo/release-action@v1
      with:
        prerelease: true
        artifacts: "protoc-gen-bq-schema*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}